---

- name: Run commands on routers
  hosts: routers
  gather_facts: false

  tasks:

    - name: Run commands
      ios_command:
        commands:
          - sh arp
          - sh ip int br
      register: result

    - name: Debug sh arp output
      debug: var=result.stdout_lines[0]

    - name: Debug sh ip int br output
      debug: var=result.stdout_lines[1]
