---

- name: Gather facts
  hosts: routers

  tasks:

    - name: Facts
      ios_facts:
        gather_subset: all

    - name: Copy facts to files
      copy:
        content: "{{ ansible_net_interfaces | to_nice_yaml }}"
        dest: "all_facts/{{ansible_net_hostname}}_intf_facts.yaml"
