---

- name: Run commands on routers
  hosts: routers
  gather_facts: false

  tasks:

    - name: Run sh arp
      ios_command:
        commands: sh arp
      register: sh_arp_output

    - name: Debug sh arp output
      debug: var=sh_arp_output
